[tool.black]
line-length = 120
target-version = ['py310']

[tool.isort]
force_sort_within_sections = true
order_by_type = false
profile = "black"
multi_line_output = 3
skip_glob = [
    "venv*",
    "helpus/resoource"
]